"""empty message

Revision ID: 05d600a5dc09
Revises: f0c61b3c08c0
Create Date: 2024-05-02 14:44:21.702252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05d600a5dc09'
down_revision = 'f0c61b3c08c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_unit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fs', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('armor', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('speed', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('range', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('primary_equipment_slots', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('secondary_equipment_slots', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('internal_slots', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_unit', schema=None) as batch_op:
        batch_op.drop_column('internal_slots')
        batch_op.drop_column('secondary_equipment_slots')
        batch_op.drop_column('primary_equipment_slots')
        batch_op.drop_column('range')
        batch_op.drop_column('speed')
        batch_op.drop_column('armor')
        batch_op.drop_column('fs')

    # ### end Alembic commands ###
