"""empty message

Revision ID: 21a4c040398b
Revises: 2bf98bc76f82
Create Date: 2024-05-06 13:28:39.240579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21a4c040398b'
down_revision = '2bf98bc76f82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('legion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_public', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('invite_code', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('legion', schema=None) as batch_op:
        batch_op.drop_column('invite_code')
        batch_op.drop_column('is_public')

    # ### end Alembic commands ###
