"""empty message

Revision ID: 2bf98bc76f82
Revises: 0bf75e6b92a4
Create Date: 2024-05-04 16:00:36.749958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bf98bc76f82'
down_revision = '0bf75e6b92a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('legion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coa_string', sa.String(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('legion', schema=None) as batch_op:
        batch_op.drop_column('coa_string')

    # ### end Alembic commands ###
