"""empty message

Revision ID: 75eb434b8dab
Revises: 
Create Date: 2024-05-02 13:43:35.882465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75eb434b8dab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unit_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_type', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('fs', sa.Integer(), nullable=False),
    sa.Column('armor', sa.Integer(), nullable=False),
    sa.Column('speed', sa.Integer(), nullable=False),
    sa.Column('range', sa.Integer(), nullable=False),
    sa.Column('special_rules', sa.Text(), nullable=False),
    sa.Column('primary_equipment_slots', sa.Integer(), nullable=True),
    sa.Column('secondary_equipment_slots', sa.Integer(), nullable=True),
    sa.Column('internal_slots', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unit_type')
    )
    op.create_table('upgrade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('compatible_unit_types', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('sign_up_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('unit_upgrades',
    sa.Column('unit_template_id', sa.Integer(), nullable=False),
    sa.Column('upgrade_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['unit_template_id'], ['unit_template.id'], ),
    sa.ForeignKeyConstraint(['upgrade_id'], ['upgrade.id'], ),
    sa.PrimaryKeyConstraint('unit_template_id', 'upgrade_id')
    )
    op.create_table('user_unit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('custom_name', sa.String(length=120), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('applied_upgrades', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['unit_template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_unit')
    op.drop_table('unit_upgrades')
    op.drop_table('user')
    op.drop_table('upgrade')
    op.drop_table('unit_template')
    # ### end Alembic commands ###
