"""empty message

Revision ID: f0c61b3c08c0
Revises: 75eb434b8dab
Create Date: 2024-05-02 14:31:06.867906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0c61b3c08c0'
down_revision = '75eb434b8dab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unit_template', schema=None) as batch_op:
        batch_op.add_column(sa.Column('structure_build_list', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('logistic_needs', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('deployment_capabilities', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unit_template', schema=None) as batch_op:
        batch_op.drop_column('deployment_capabilities')
        batch_op.drop_column('logistic_needs')
        batch_op.drop_column('structure_build_list')

    # ### end Alembic commands ###
