-- Generated by scripts/generate-classes-catalogue.ts from rules/Classes.html.
-- Do not hand-edit. Companion FS values are preserved as catalogue data and never
-- converted into the active V5 Hits, attack, or requisition models.

INSERT INTO unit_class_definitions (
  id, ruleset_id, name, category, health_model, max_health, armor, defense,
  speed_quarters, sensor_range, requisition_cost, definition_status, source, notes, definition_json
) VALUES
  ('unit-sappers', 'ruleset-v5-core-curated-1', 'Sappers', 'SUPPORT', 'FORCE_STRENGTH', 2, 0, 0, 4, 0, NULL, 'legacy', 'Classes.html row 8 / Sappers', 'Companion class preserved exactly; gameplay and requisition remain blocked by RC-UNIT-015.', '{"sourceRow":8,"description":"Sappers A smaller group of engineers trained move around quietly. Can do everything the Engineers do but quietly. Sappers are an elite group and very few in number.","raw":{"forceStrength":2,"armor":0,"speed":1,"range":1,"cost":null},"specialRules":"Stealth Engineers - Can Build and Repair Structures and Repair Vehicles at 2FS per Repair Action. Can Build Limited Structures. Can Take Limited SF Equipment. Has Stealth Each Build Action makes 3 Building Progress on the project using up 3 Building Supply. Building Supply can be reloaded for 1 General Supply crate. Sappers Have 6/6 Build Supply and come with mines. Mines - Can set mines. Explodes on enemy contact. Structures - Sensor Tower: Build in a hex, reveal area 1 hex out around Sensor Tower. Weapon Emplacement Equipment Upgrades Primary Equipment Slot 1 Secondary Equipment Slot 1","equipmentSlots":{"PRIMARY":1,"SECONDARY":1},"gameplayGaps":["SAPPER_STRUCTURE_LIST","MINES","BUILD_SUPPLY","STEALTH_CONSTRUCTION"],"canonicalActivation":"CATALOGUED","conflictIds":["RC-UNIT-015","RC-V5-014"]}'),
  ('unit-mechanized-infantry', 'ruleset-v5-core-curated-1', 'Mechanized Infantry', 'ARMOUR', 'FORCE_STRENGTH', 3, 2, 0, 12, 0, NULL, 'legacy', 'Classes.html row 10 / Mechanized Infantry', 'Companion class preserved exactly; gameplay and requisition remain blocked by RC-UNIT-015.', '{"sourceRow":10,"description":"Mechanized Infantry The only vehicle based unit that can hold a hex like infantry but only from one direction; mechanized infantry can hold 1 forward hex line instead of 3. Mechanized infantry are infantry deployed from armored fighting vehicles","raw":{"forceStrength":3,"armor":2,"speed":3,"range":2,"cost":null},"specialRules":"Can Hold a Center Hex Line Like Infantry. Has the range and speed of a vehicle without the AP of a tank. Can take upgrades from both infantry and vehicle lists. All AP, Armor and Speed upgrades must come from the vehicle list. 1 Primary, 1 Secondary, 1 Internal slot.","equipmentSlots":{"PRIMARY":1,"SECONDARY":1,"INTERNAL":1},"gameplayGaps":["FORWARD_LINE_CONTROL","MIXED_EQUIPMENT_POLICY","FS_VEHICLE_DAMAGE_MODEL"],"canonicalActivation":"CATALOGUED","conflictIds":["RC-UNIT-015","RC-V5-014"]}'),
  ('unit-light-battle-tank', 'ruleset-v5-core-curated-1', 'Light Battle Tank', 'ARMOUR', 'FORCE_STRENGTH', 3, 2, 0, 12, 0, NULL, 'legacy', 'Classes.html row 14 / Light Battle Tank', 'Companion class preserved exactly; gameplay and requisition remain blocked by RC-UNIT-015.', '{"sourceRow":14,"description":"Light Battle Tank Uses for scouting duty, front line combat and capable of being dropped with para-troopers forces out of the back of a Heavy Air Transport. Unlike any other type of tank. These tanks are tipically faster but with less armor then a standard main battle tank.","raw":{"forceStrength":3,"armor":2,"speed":3,"range":2,"cost":null},"specialRules":"AP 2 Fits Inside and be air dropped out of a Heavy Air Transport Armor Weak Spot - Rear Hex Wall Upgrades 1 Secondary 1 Internal","equipmentSlots":{"SECONDARY":1,"INTERNAL":1},"gameplayGaps":["FS_VEHICLE_DAMAGE_MODEL","WEAPON_DAMAGE_PROFILE","HAT_TANK_AIRDROP"],"canonicalActivation":"CATALOGUED","conflictIds":["RC-UNIT-015","RC-V5-014"]}'),
  ('unit-heavy-battle-tank', 'ruleset-v5-core-curated-1', 'Heavy Battle Tank', 'ARMOUR', 'FORCE_STRENGTH', 3, 4, 0, 8, 0, NULL, 'legacy', 'Classes.html row 16 / Heavy Battle Tank', 'Companion class preserved exactly; gameplay and requisition remain blocked by RC-UNIT-015.', '{"sourceRow":16,"description":"Heavy Battle Tank Heavyer and larger than a standard main battle tank. Up armored with a longer barreled main cannon for increased range. This increase weight limits the transportation options for the Heavy Battle tank. Does not fit inside the Heavy Air Transport.","raw":{"forceStrength":3,"armor":4,"speed":2,"range":3,"cost":null},"specialRules":"AP 2 Armor Weak Spot - Rear Hex Wall Upgrades 1 Secondary 1 Internal","equipmentSlots":{"SECONDARY":1,"INTERNAL":1},"gameplayGaps":["FS_VEHICLE_DAMAGE_MODEL","WEAPON_DAMAGE_PROFILE","HEAVY_TRANSPORT_POLICY"],"canonicalActivation":"CATALOGUED","conflictIds":["RC-UNIT-015","RC-V5-014"]}'),
  ('unit-super-heavy-tank', 'ruleset-v5-core-curated-1', 'Super Heavy Tank', 'ARMOUR', 'FORCE_STRENGTH', 4, 5, 0, 4, 0, NULL, 'legacy', 'Classes.html row 17 / Super Heavy Tank', 'Companion class preserved exactly; gameplay and requisition remain blocked by RC-UNIT-015.', '{"sourceRow":17,"description":"Super Heavy Tank \"Single Tank\" This is the king or armored combat. Dual main weapon systems bring more firepower to the field, each cannon larger than even the Heavy Battle Tank. Only specialized transports can move this Behemoth. The biggest issue for a commander of this unit is incredably limited mobility. Unlike every other tank unit this unit is a single tank.","raw":{"forceStrength":4,"armor":5,"speed":1,"range":3,"cost":null},"specialRules":"AP 5 Fires TWICE with each action. Armor Weak Spot - Rear Hex Wall Upgrades 2 Secondary 2 Internal","equipmentSlots":{"SECONDARY":2,"INTERNAL":2},"gameplayGaps":["FS_VEHICLE_DAMAGE_MODEL","DUAL_CANNON_ATTACK","WEAPON_DAMAGE_PROFILE","SPECIAL_TRANSPORT_POLICY"],"canonicalActivation":"CATALOGUED","conflictIds":["RC-UNIT-015","RC-V5-014"]}'),
  ('unit-light-artillery', 'ruleset-v5-core-curated-1', 'Light Artillery', 'SUPPORT', 'FORCE_STRENGTH', 2, 0, 0, 4, 0, NULL, 'legacy', 'Classes.html row 19 / Light Artillery', 'Companion class preserved exactly; gameplay and requisition remain blocked by RC-UNIT-015.', '{"sourceRow":19,"description":"Light Arty A set of light guns able to be deployed and rain fire on distant enemies. While it doesn''t have the damage potential of the heavy artillery these field guns can be moved by the infantry manning them and transported much easier. Light Artillery can be para-dropped from a heavy air transport or brought down in Heavy Drop Pods if an obital has the equipment.","raw":{"forceStrength":2,"armor":0,"speed":1,"range":5,"cost":"0"},"specialRules":"2 Damage, Range 5 Can''t Attack Unless Deployed Action: Deploy - sets up guns to fire. Can''t move while deployed. Action: Abandon Guns - flee from your quipment and turn into a 1FS 1 Speed Infantry Unit. Can retreieve new equipment from a supply depot for 5 supply crates 1 Time for the entire campaign. This unit can dropped from a orbital with the Heavy Drop Pod Upgrade. This unit can para-drop from Heavy Transport Aerospace Craft. 2 Attacks per Action ! Can be all on 1 Hex or split! Indirect Fire - Doesn''t need direct LOS to fire on hostiles and hits all units in HEX targeted. Upgrades 1 Secondary 2 Internal","equipmentSlots":{"SECONDARY":1,"INTERNAL":2},"gameplayGaps":["FIXED_DAMAGE","TWO_ATTACK_SPLIT_FIRE","AREA_HEX_DAMAGE","ABANDON_GUNS","CAMPAIGN_REPLACEMENT"],"canonicalActivation":"CATALOGUED","conflictIds":["RC-UNIT-015","RC-V5-014"]}'),
  ('unit-heavy-artillery', 'ruleset-v5-core-curated-1', 'Heavy Artillery', 'SUPPORT', 'FORCE_STRENGTH', 3, 0, 0, 0, 0, NULL, 'legacy', 'Classes.html row 20 / Heavy Artillery', 'Companion class preserved exactly; gameplay and requisition remain blocked by RC-UNIT-015.', '{"sourceRow":20,"description":"Heavy Arty Called the \"King of the Battlefield\" for a reason. Artillery lobs rounds at the longest ranges. Weakening targets, supporting friendlies and opening holes in the front lines when needed. While having the most out going damage potential Heavy Artillery is the most limited in moblity. Being unable to move without support.","raw":{"forceStrength":3,"armor":0,"speed":0,"range":8,"cost":"0"},"specialRules":"3 Damage, Range 8 Can''t Attack Unless Deployed Action: Deploy - sets up guns to fire. Can''t move while deployed. Action: Abandon Guns - flee from your quipment and tunrin into a 1FS 1 Speed Infantry Unit. Can retreieve new equipment from a supply depot for 5 supply crates. Can be loaded into a Heavy Air Transport. 1 Time for the entire campaign 3 Attacks per Action ! Can be all on 1 Hex or split! Indirect Fire - Doesn''t need direct LOS to fire on hostiles and hits all units in HEX targeted. Upgrades 1 Secondary 2 Internal","equipmentSlots":{"SECONDARY":1,"INTERNAL":2},"gameplayGaps":["FIXED_DAMAGE","THREE_ATTACK_SPLIT_FIRE","AREA_HEX_DAMAGE","ABANDON_GUNS","CAMPAIGN_REPLACEMENT"],"canonicalActivation":"CATALOGUED","conflictIds":["RC-UNIT-015","RC-V5-014"]}'),
  ('unit-self-propelled-artillery', 'ruleset-v5-core-curated-1', 'Self-Propelled Artillery', 'SUPPORT', 'FORCE_STRENGTH', 2, 2, 0, 8, 0, NULL, 'legacy', 'Classes.html row 21 / Self-Propelled Artillery', 'Companion class preserved exactly; gameplay and requisition remain blocked by RC-UNIT-015.', '{"sourceRow":21,"description":"Self-Propelled The most mobile of the artillery units. Guns mounted on tracks or wheels.. While they can get up and move and fire without needing to setup and deploy SPG''s do not get multiple shots like other artillery types.","raw":{"forceStrength":2,"armor":2,"speed":2,"range":4,"cost":"0"},"specialRules":"Minimum Range 2, Choose Wheeled or Tracked. (Comes with (5) AP Rounds, Gift from Haven. Once Used they are gone forever) Indirect Fire - Doesn''t need direct LOS to fire on hostiles and hits all units in HEX targeted. Upgrades 1 Secondary 2 Internal","equipmentSlots":{"SECONDARY":1,"INTERNAL":2},"gameplayGaps":["FS_VEHICLE_DAMAGE_MODEL","FIXED_DAMAGE","MINIMUM_RANGE","FINITE_AP_ROUNDS","AREA_HEX_DAMAGE"],"canonicalActivation":"CATALOGUED","conflictIds":["RC-UNIT-015","RC-V5-014"]}'),
  ('unit-vtol-troop-airlift', 'ruleset-v5-core-curated-1', 'VTOL Heavy Troop Airlift', 'AEROSPACE', 'FORCE_STRENGTH', 3, 1, 0, 20, 0, NULL, 'legacy', 'Classes.html row 24 / VTOL Heavy Troop Airlift', 'Companion class preserved exactly; gameplay and requisition remain blocked by RC-UNIT-015.', '{"sourceRow":24,"description":"VTOL Heavy Troop Airlift A infantry focused troop transport that can move multiple platoon of infantry to and from the battlefield as well as some Supply inside its dedicated bay. Forward mounted light weapon offers cover for ground forces.","raw":{"forceStrength":3,"armor":1,"speed":5,"range":1,"cost":"0"},"specialRules":"2 Infantry Unit Capactiy or 1 Supply Cargo Rearm after every FS based Attack Comes with Repelling gear allowing infantry to drop from the VTOL and garrison a building without using an action or requiring the VTOL to land. Upgrades - 1 Light Weapon Mounts 1 Internal Upgrades","equipmentSlots":{"LIGHT":1,"INTERNAL":1},"gameplayGaps":["FS_AEROSPACE_DAMAGE_MODEL","TROOP_OR_SUPPLY_CAPACITY","RAPPELLING_GARRISON","FS_BASED_REARM"],"canonicalActivation":"CATALOGUED","conflictIds":["RC-UNIT-015","RC-V5-014"]}'),
  ('unit-vtol-multipurpose-airlift', 'ruleset-v5-core-curated-1', 'VTOL Multi-Purpose Airlift', 'AEROSPACE', 'FORCE_STRENGTH', 3, 1, 0, 20, 0, NULL, 'legacy', 'Classes.html row 25 / VTOL Multi-Purpose Airlift', 'Companion class preserved exactly; gameplay and requisition remain blocked by RC-UNIT-015.', '{"sourceRow":25,"description":"VTOL Multi-Purpose Airlift A smaller VTOL outfitted with enough space for an infantry unit and a single light vehicle unit. Some call it a pelican others with taste a warden.","raw":{"forceStrength":3,"armor":1,"speed":5,"range":1,"cost":"0"},"specialRules":"1 Infantry Unit Capacity or one supply cargo and 1 Light Vehicle Unit Capacity Rearm after every FS based Attack Upgrades - 1 Light Weapon Mounts 1 Internal Upgrades","equipmentSlots":{"LIGHT":1,"INTERNAL":1},"gameplayGaps":["FS_AEROSPACE_DAMAGE_MODEL","SIMULTANEOUS_PERSONNEL_AND_VEHICLE_CARGO","FS_BASED_REARM"],"canonicalActivation":"CATALOGUED","conflictIds":["RC-UNIT-015","RC-V5-014"]}'),
  ('unit-vtol-heavy-lift', 'ruleset-v5-core-curated-1', 'VTOL Heavy Lift', 'AEROSPACE', 'FORCE_STRENGTH', 3, 3, 0, 20, 0, NULL, 'legacy', 'Classes.html row 26 / VTOL Heavy Lift', 'Companion class preserved exactly; gameplay and requisition remain blocked by RC-UNIT-015.', '{"sourceRow":26,"description":"VTOL Heavy Lift Refit for 1 purpose.. To move the heavy equipment. Be they an objective in the field that no one else can move or a friendly Super heavy tank / Mech to bring the pain. Some argue the most powerful team is a VTOL Heavy Lift with a friend.","raw":{"forceStrength":3,"armor":3,"speed":5,"range":0,"cost":"0"},"specialRules":"VTOL Craft No Weapon Can move a single Mech or a Single SHBT, or a Heavy Tank Unit Hollow Mid Section for Lifting Massive Equipment. Can lift 1 Supply Cargo Upgrades - 1 Light Weapon Mounts 1 Internal Upgrades","equipmentSlots":{"LIGHT":1,"INTERNAL":1},"gameplayGaps":["FS_AEROSPACE_DAMAGE_MODEL","EXTERNAL_HEAVY_LIFT","OBJECTIVE_CARGO","HEAVY_TRANSPORT_CAPACITY"],"canonicalActivation":"CATALOGUED","conflictIds":["RC-UNIT-015","RC-V5-014"]}'),
  ('unit-medium-mech', 'ruleset-v5-core-curated-1', 'Medium Mech', 'MECH', 'FORCE_STRENGTH', 4, 2, 0, 12, 0, NULL, 'legacy', 'Classes.html row 31 / Medium Mech', 'Companion class preserved exactly; gameplay and requisition remain blocked by RC-UNIT-015.', '{"sourceRow":31,"description":"Medium Mech Still decently fast for a mech, the medium mech has more space for weapons and equipment.","raw":{"forceStrength":4,"armor":2,"speed":3,"range":0,"cost":"..1"},"specialRules":"2/4 Can''t reload there weapons without being at a supply point due to the scale of the weapon systems. This mech comes with No Weapons. You can transfer your prior Mechs Weapon Mechs can fire all weapons at once or 1 at a time. Legged - Can see over Terrain at lvl 1 higher. Can Crouch to use lvl 1 terrain as cover from direct weapons if blocking LOS.","equipmentSlots":{"EXTERNAL":2,"INTERNAL":4},"gameplayGaps":["FS_MECH_DAMAGE_MODEL","MULTIWEAPON_REFIT","LEG_HEIGHT_LOS","CROUCH_COVER","DOTTED_REQUISITION_COST"],"canonicalActivation":"CATALOGUED","conflictIds":["RC-UNIT-015","RC-V5-014"]}'),
  ('unit-heavy-mech', 'ruleset-v5-core-curated-1', 'Heavy Mech', 'MECH', 'FORCE_STRENGTH', 5, 3, 0, 8, 0, NULL, 'legacy', 'Classes.html row 32 / Heavy Mech', 'Companion class preserved exactly; gameplay and requisition remain blocked by RC-UNIT-015.', '{"sourceRow":32,"description":"Heavy Mech Slow but incredably well armored. The heavy mech towers over the battlefield. With its large collections of weapons which can all be fired at once or 1 at a time. If a heavy Mech sees a problem. It probably has a solution.","raw":{"forceStrength":5,"armor":3,"speed":2,"range":0,"cost":"....2"},"specialRules":"3/4 Can''t reload there weapons without being at a supply point due to the scale of the weapon systems. This mech comes with No Weapons. You can transfer your prior Mechs Weapons Mechs can fire all weapons at once or 1 at a time. Legged - Can see over Terrain at lvl 1 higher.","equipmentSlots":{"EXTERNAL":3,"INTERNAL":4},"gameplayGaps":["FS_MECH_DAMAGE_MODEL","MULTIWEAPON_REFIT","LEG_HEIGHT_LOS","DOTTED_REQUISITION_COST"],"canonicalActivation":"CATALOGUED","conflictIds":["RC-UNIT-015","RC-V5-014"]}')
ON CONFLICT(id, ruleset_id) DO UPDATE SET
  name=excluded.name, category=excluded.category, health_model=excluded.health_model,
  max_health=excluded.max_health, armor=excluded.armor, defense=excluded.defense,
  speed_quarters=excluded.speed_quarters, sensor_range=excluded.sensor_range,
  requisition_cost=excluded.requisition_cost, definition_status=excluded.definition_status,
  source=excluded.source, notes=excluded.notes, definition_json=excluded.definition_json;

INSERT INTO unit_definition_profiles (
  unit_definition_id, ruleset_id, movement_profile_id, durability_profile_id,
  cargo_profile_id, supply_profile_id, deployment_profile_id, profile_json
) VALUES
  ('unit-sappers', 'ruleset-v5-core-curated-1', 'movement-infantry-ground', 'durability-personnel-fs', NULL, NULL, 'deployment-ground', '{"canonicalActivation":"CATALOGUED","conflictIds":["RC-UNIT-015"]}'),
  ('unit-mechanized-infantry', 'ruleset-v5-core-curated-1', 'movement-ground-standard', 'durability-personnel-fs', NULL, NULL, 'deployment-ground', '{"canonicalActivation":"CATALOGUED","conflictIds":["RC-UNIT-015"]}'),
  ('unit-light-battle-tank', 'ruleset-v5-core-curated-1', 'movement-tracked-ground', 'durability-personnel-fs', NULL, NULL, 'deployment-ground', '{"canonicalActivation":"CATALOGUED","conflictIds":["RC-UNIT-015"]}'),
  ('unit-heavy-battle-tank', 'ruleset-v5-core-curated-1', 'movement-tracked-ground', 'durability-personnel-fs', NULL, NULL, 'deployment-ground', '{"canonicalActivation":"CATALOGUED","conflictIds":["RC-UNIT-015"]}'),
  ('unit-super-heavy-tank', 'ruleset-v5-core-curated-1', 'movement-tracked-ground', 'durability-personnel-fs', NULL, NULL, 'deployment-ground', '{"canonicalActivation":"CATALOGUED","conflictIds":["RC-UNIT-015"]}'),
  ('unit-light-artillery', 'ruleset-v5-core-curated-1', 'movement-ground-standard', 'durability-personnel-fs', NULL, NULL, 'deployment-ground', '{"canonicalActivation":"CATALOGUED","conflictIds":["RC-UNIT-015"]}'),
  ('unit-heavy-artillery', 'ruleset-v5-core-curated-1', 'movement-ground-standard', 'durability-personnel-fs', NULL, NULL, 'deployment-ground', '{"canonicalActivation":"CATALOGUED","conflictIds":["RC-UNIT-015"]}'),
  ('unit-self-propelled-artillery', 'ruleset-v5-core-curated-1', 'movement-tracked-ground', 'durability-personnel-fs', NULL, NULL, 'deployment-ground', '{"canonicalActivation":"CATALOGUED","conflictIds":["RC-UNIT-015"]}'),
  ('unit-vtol-troop-airlift', 'ruleset-v5-core-curated-1', 'movement-vtol', 'durability-personnel-fs', NULL, NULL, 'deployment-vtol', '{"canonicalActivation":"CATALOGUED","conflictIds":["RC-UNIT-015"]}'),
  ('unit-vtol-multipurpose-airlift', 'ruleset-v5-core-curated-1', 'movement-vtol', 'durability-personnel-fs', NULL, NULL, 'deployment-vtol', '{"canonicalActivation":"CATALOGUED","conflictIds":["RC-UNIT-015"]}'),
  ('unit-vtol-heavy-lift', 'ruleset-v5-core-curated-1', 'movement-vtol', 'durability-personnel-fs', NULL, NULL, 'deployment-vtol', '{"canonicalActivation":"CATALOGUED","conflictIds":["RC-UNIT-015"]}'),
  ('unit-medium-mech', 'ruleset-v5-core-curated-1', 'movement-mech', 'durability-personnel-fs', NULL, NULL, 'deployment-ground', '{"canonicalActivation":"CATALOGUED","conflictIds":["RC-UNIT-015"]}'),
  ('unit-heavy-mech', 'ruleset-v5-core-curated-1', 'movement-mech', 'durability-personnel-fs', NULL, NULL, 'deployment-ground', '{"canonicalActivation":"CATALOGUED","conflictIds":["RC-UNIT-015"]}')
ON CONFLICT(unit_definition_id, ruleset_id) DO UPDATE SET
  movement_profile_id=excluded.movement_profile_id, durability_profile_id=excluded.durability_profile_id,
  cargo_profile_id=excluded.cargo_profile_id, supply_profile_id=excluded.supply_profile_id,
  deployment_profile_id=excluded.deployment_profile_id, profile_json=excluded.profile_json;

INSERT INTO unit_definition_tags (unit_definition_id, ruleset_id, tag_id) VALUES
  ('unit-sappers', 'ruleset-v5-core-curated-1', 'tag-infantry'),
  ('unit-sappers', 'ruleset-v5-core-curated-1', 'tag-infantry-stealth'),
  ('unit-sappers', 'ruleset-v5-core-curated-1', 'tag-engineer'),
  ('unit-mechanized-infantry', 'ruleset-v5-core-curated-1', 'tag-infantry'),
  ('unit-mechanized-infantry', 'ruleset-v5-core-curated-1', 'tag-vehicle'),
  ('unit-mechanized-infantry', 'ruleset-v5-core-curated-1', 'tag-armoured'),
  ('unit-mechanized-infantry', 'ruleset-v5-core-curated-1', 'tag-transport'),
  ('unit-light-battle-tank', 'ruleset-v5-core-curated-1', 'tag-vehicle'),
  ('unit-light-battle-tank', 'ruleset-v5-core-curated-1', 'tag-armoured'),
  ('unit-light-battle-tank', 'ruleset-v5-core-curated-1', 'tag-light'),
  ('unit-heavy-battle-tank', 'ruleset-v5-core-curated-1', 'tag-vehicle'),
  ('unit-heavy-battle-tank', 'ruleset-v5-core-curated-1', 'tag-armoured'),
  ('unit-heavy-battle-tank', 'ruleset-v5-core-curated-1', 'tag-heavy'),
  ('unit-super-heavy-tank', 'ruleset-v5-core-curated-1', 'tag-vehicle'),
  ('unit-super-heavy-tank', 'ruleset-v5-core-curated-1', 'tag-armoured'),
  ('unit-super-heavy-tank', 'ruleset-v5-core-curated-1', 'tag-heavy'),
  ('unit-super-heavy-tank', 'ruleset-v5-core-curated-1', 'tag-ponderous'),
  ('unit-light-artillery', 'ruleset-v5-core-curated-1', 'tag-artillery'),
  ('unit-light-artillery', 'ruleset-v5-core-curated-1', 'tag-indirect-fire'),
  ('unit-heavy-artillery', 'ruleset-v5-core-curated-1', 'tag-artillery'),
  ('unit-heavy-artillery', 'ruleset-v5-core-curated-1', 'tag-indirect-fire'),
  ('unit-heavy-artillery', 'ruleset-v5-core-curated-1', 'tag-ponderous'),
  ('unit-self-propelled-artillery', 'ruleset-v5-core-curated-1', 'tag-vehicle'),
  ('unit-self-propelled-artillery', 'ruleset-v5-core-curated-1', 'tag-armoured'),
  ('unit-self-propelled-artillery', 'ruleset-v5-core-curated-1', 'tag-artillery'),
  ('unit-self-propelled-artillery', 'ruleset-v5-core-curated-1', 'tag-indirect-fire'),
  ('unit-vtol-troop-airlift', 'ruleset-v5-core-curated-1', 'tag-vehicle'),
  ('unit-vtol-troop-airlift', 'ruleset-v5-core-curated-1', 'tag-aerospace'),
  ('unit-vtol-troop-airlift', 'ruleset-v5-core-curated-1', 'tag-atmo-flight'),
  ('unit-vtol-troop-airlift', 'ruleset-v5-core-curated-1', 'tag-vtol'),
  ('unit-vtol-troop-airlift', 'ruleset-v5-core-curated-1', 'tag-transport'),
  ('unit-vtol-multipurpose-airlift', 'ruleset-v5-core-curated-1', 'tag-vehicle'),
  ('unit-vtol-multipurpose-airlift', 'ruleset-v5-core-curated-1', 'tag-aerospace'),
  ('unit-vtol-multipurpose-airlift', 'ruleset-v5-core-curated-1', 'tag-atmo-flight'),
  ('unit-vtol-multipurpose-airlift', 'ruleset-v5-core-curated-1', 'tag-vtol'),
  ('unit-vtol-multipurpose-airlift', 'ruleset-v5-core-curated-1', 'tag-transport'),
  ('unit-vtol-heavy-lift', 'ruleset-v5-core-curated-1', 'tag-vehicle'),
  ('unit-vtol-heavy-lift', 'ruleset-v5-core-curated-1', 'tag-aerospace'),
  ('unit-vtol-heavy-lift', 'ruleset-v5-core-curated-1', 'tag-atmo-flight'),
  ('unit-vtol-heavy-lift', 'ruleset-v5-core-curated-1', 'tag-vtol'),
  ('unit-vtol-heavy-lift', 'ruleset-v5-core-curated-1', 'tag-transport'),
  ('unit-vtol-heavy-lift', 'ruleset-v5-core-curated-1', 'tag-heavy'),
  ('unit-vtol-heavy-lift', 'ruleset-v5-core-curated-1', 'tag-logistics'),
  ('unit-medium-mech', 'ruleset-v5-core-curated-1', 'tag-vehicle'),
  ('unit-medium-mech', 'ruleset-v5-core-curated-1', 'tag-armoured'),
  ('unit-medium-mech', 'ruleset-v5-core-curated-1', 'tag-mech'),
  ('unit-heavy-mech', 'ruleset-v5-core-curated-1', 'tag-vehicle'),
  ('unit-heavy-mech', 'ruleset-v5-core-curated-1', 'tag-armoured'),
  ('unit-heavy-mech', 'ruleset-v5-core-curated-1', 'tag-mech'),
  ('unit-heavy-mech', 'ruleset-v5-core-curated-1', 'tag-heavy'),
  ('unit-heavy-mech', 'ruleset-v5-core-curated-1', 'tag-ponderous')
ON CONFLICT(unit_definition_id, ruleset_id, tag_id) DO NOTHING;

INSERT INTO unit_definition_abilities (unit_definition_id, ruleset_id, ability_id, source_kind) VALUES
  ('unit-sappers', 'ruleset-v5-core-curated-1', 'ability-infantry-stealth', 'BASE'),
  ('unit-sappers', 'ruleset-v5-core-curated-1', 'ability-construct', 'BASE'),
  ('unit-sappers', 'ruleset-v5-core-curated-1', 'ability-repair-vehicle', 'BASE'),
  ('unit-light-artillery', 'ruleset-v5-core-curated-1', 'ability-deploy-platform', 'BASE'),
  ('unit-light-artillery', 'ruleset-v5-core-curated-1', 'ability-indirect-fire', 'BASE'),
  ('unit-heavy-artillery', 'ruleset-v5-core-curated-1', 'ability-deploy-platform', 'BASE'),
  ('unit-heavy-artillery', 'ruleset-v5-core-curated-1', 'ability-indirect-fire', 'BASE'),
  ('unit-self-propelled-artillery', 'ruleset-v5-core-curated-1', 'ability-indirect-fire', 'BASE'),
  ('unit-vtol-troop-airlift', 'ruleset-v5-core-curated-1', 'ability-flight-path', 'BASE'),
  ('unit-vtol-troop-airlift', 'ruleset-v5-core-curated-1', 'ability-transport-cargo', 'BASE'),
  ('unit-vtol-multipurpose-airlift', 'ruleset-v5-core-curated-1', 'ability-flight-path', 'BASE'),
  ('unit-vtol-multipurpose-airlift', 'ruleset-v5-core-curated-1', 'ability-transport-cargo', 'BASE'),
  ('unit-vtol-heavy-lift', 'ruleset-v5-core-curated-1', 'ability-flight-path', 'BASE'),
  ('unit-vtol-heavy-lift', 'ruleset-v5-core-curated-1', 'ability-transport-cargo', 'BASE')
ON CONFLICT(unit_definition_id, ruleset_id, ability_id, source_kind) DO NOTHING;

INSERT INTO unit_equipment_slot_definitions (
  unit_definition_id, ruleset_id, slot_type, slot_count, eligibility_json, source_path, source_locator
) VALUES
  ('unit-sappers', 'ruleset-v5-core-curated-1', 'PRIMARY', 1, '{"canonicalActivation":"CATALOGUED","conflictIds":["RC-UNIT-015"]}', 'rules/Classes.html', 'Sappers / row 8'),
  ('unit-sappers', 'ruleset-v5-core-curated-1', 'SECONDARY', 1, '{"canonicalActivation":"CATALOGUED","conflictIds":["RC-UNIT-015"]}', 'rules/Classes.html', 'Sappers / row 8'),
  ('unit-mechanized-infantry', 'ruleset-v5-core-curated-1', 'PRIMARY', 1, '{"canonicalActivation":"CATALOGUED","conflictIds":["RC-UNIT-015"]}', 'rules/Classes.html', 'Mechanized Infantry / row 10'),
  ('unit-mechanized-infantry', 'ruleset-v5-core-curated-1', 'SECONDARY', 1, '{"canonicalActivation":"CATALOGUED","conflictIds":["RC-UNIT-015"]}', 'rules/Classes.html', 'Mechanized Infantry / row 10'),
  ('unit-mechanized-infantry', 'ruleset-v5-core-curated-1', 'INTERNAL', 1, '{"canonicalActivation":"CATALOGUED","conflictIds":["RC-UNIT-015"]}', 'rules/Classes.html', 'Mechanized Infantry / row 10'),
  ('unit-light-battle-tank', 'ruleset-v5-core-curated-1', 'SECONDARY', 1, '{"canonicalActivation":"CATALOGUED","conflictIds":["RC-UNIT-015"]}', 'rules/Classes.html', 'Light Battle Tank / row 14'),
  ('unit-light-battle-tank', 'ruleset-v5-core-curated-1', 'INTERNAL', 1, '{"canonicalActivation":"CATALOGUED","conflictIds":["RC-UNIT-015"]}', 'rules/Classes.html', 'Light Battle Tank / row 14'),
  ('unit-heavy-battle-tank', 'ruleset-v5-core-curated-1', 'SECONDARY', 1, '{"canonicalActivation":"CATALOGUED","conflictIds":["RC-UNIT-015"]}', 'rules/Classes.html', 'Heavy Battle Tank / row 16'),
  ('unit-heavy-battle-tank', 'ruleset-v5-core-curated-1', 'INTERNAL', 1, '{"canonicalActivation":"CATALOGUED","conflictIds":["RC-UNIT-015"]}', 'rules/Classes.html', 'Heavy Battle Tank / row 16'),
  ('unit-super-heavy-tank', 'ruleset-v5-core-curated-1', 'SECONDARY', 2, '{"canonicalActivation":"CATALOGUED","conflictIds":["RC-UNIT-015"]}', 'rules/Classes.html', 'Super Heavy Tank / row 17'),
  ('unit-super-heavy-tank', 'ruleset-v5-core-curated-1', 'INTERNAL', 2, '{"canonicalActivation":"CATALOGUED","conflictIds":["RC-UNIT-015"]}', 'rules/Classes.html', 'Super Heavy Tank / row 17'),
  ('unit-light-artillery', 'ruleset-v5-core-curated-1', 'SECONDARY', 1, '{"canonicalActivation":"CATALOGUED","conflictIds":["RC-UNIT-015"]}', 'rules/Classes.html', 'Light Artillery / row 19'),
  ('unit-light-artillery', 'ruleset-v5-core-curated-1', 'INTERNAL', 2, '{"canonicalActivation":"CATALOGUED","conflictIds":["RC-UNIT-015"]}', 'rules/Classes.html', 'Light Artillery / row 19'),
  ('unit-heavy-artillery', 'ruleset-v5-core-curated-1', 'SECONDARY', 1, '{"canonicalActivation":"CATALOGUED","conflictIds":["RC-UNIT-015"]}', 'rules/Classes.html', 'Heavy Artillery / row 20'),
  ('unit-heavy-artillery', 'ruleset-v5-core-curated-1', 'INTERNAL', 2, '{"canonicalActivation":"CATALOGUED","conflictIds":["RC-UNIT-015"]}', 'rules/Classes.html', 'Heavy Artillery / row 20'),
  ('unit-self-propelled-artillery', 'ruleset-v5-core-curated-1', 'SECONDARY', 1, '{"canonicalActivation":"CATALOGUED","conflictIds":["RC-UNIT-015"]}', 'rules/Classes.html', 'Self-Propelled Artillery / row 21'),
  ('unit-self-propelled-artillery', 'ruleset-v5-core-curated-1', 'INTERNAL', 2, '{"canonicalActivation":"CATALOGUED","conflictIds":["RC-UNIT-015"]}', 'rules/Classes.html', 'Self-Propelled Artillery / row 21'),
  ('unit-vtol-troop-airlift', 'ruleset-v5-core-curated-1', 'LIGHT', 1, '{"canonicalActivation":"CATALOGUED","conflictIds":["RC-UNIT-015"]}', 'rules/Classes.html', 'VTOL Heavy Troop Airlift / row 24'),
  ('unit-vtol-troop-airlift', 'ruleset-v5-core-curated-1', 'INTERNAL', 1, '{"canonicalActivation":"CATALOGUED","conflictIds":["RC-UNIT-015"]}', 'rules/Classes.html', 'VTOL Heavy Troop Airlift / row 24'),
  ('unit-vtol-multipurpose-airlift', 'ruleset-v5-core-curated-1', 'LIGHT', 1, '{"canonicalActivation":"CATALOGUED","conflictIds":["RC-UNIT-015"]}', 'rules/Classes.html', 'VTOL Multi-Purpose Airlift / row 25'),
  ('unit-vtol-multipurpose-airlift', 'ruleset-v5-core-curated-1', 'INTERNAL', 1, '{"canonicalActivation":"CATALOGUED","conflictIds":["RC-UNIT-015"]}', 'rules/Classes.html', 'VTOL Multi-Purpose Airlift / row 25'),
  ('unit-vtol-heavy-lift', 'ruleset-v5-core-curated-1', 'LIGHT', 1, '{"canonicalActivation":"CATALOGUED","conflictIds":["RC-UNIT-015"]}', 'rules/Classes.html', 'VTOL Heavy Lift / row 26'),
  ('unit-vtol-heavy-lift', 'ruleset-v5-core-curated-1', 'INTERNAL', 1, '{"canonicalActivation":"CATALOGUED","conflictIds":["RC-UNIT-015"]}', 'rules/Classes.html', 'VTOL Heavy Lift / row 26'),
  ('unit-medium-mech', 'ruleset-v5-core-curated-1', 'EXTERNAL', 2, '{"canonicalActivation":"CATALOGUED","conflictIds":["RC-UNIT-015"]}', 'rules/Classes.html', 'Medium Mech / row 31'),
  ('unit-medium-mech', 'ruleset-v5-core-curated-1', 'INTERNAL', 4, '{"canonicalActivation":"CATALOGUED","conflictIds":["RC-UNIT-015"]}', 'rules/Classes.html', 'Medium Mech / row 31'),
  ('unit-heavy-mech', 'ruleset-v5-core-curated-1', 'EXTERNAL', 3, '{"canonicalActivation":"CATALOGUED","conflictIds":["RC-UNIT-015"]}', 'rules/Classes.html', 'Heavy Mech / row 32'),
  ('unit-heavy-mech', 'ruleset-v5-core-curated-1', 'INTERNAL', 4, '{"canonicalActivation":"CATALOGUED","conflictIds":["RC-UNIT-015"]}', 'rules/Classes.html', 'Heavy Mech / row 32')
ON CONFLICT(unit_definition_id, ruleset_id, slot_type) DO UPDATE SET
  slot_count=excluded.slot_count, eligibility_json=excluded.eligibility_json,
  source_path=excluded.source_path, source_locator=excluded.source_locator;

INSERT INTO ruleset_implementation_overlays (
  definition_kind, definition_id, ruleset_id, implementation_status,
  requisition_status, availability_status, executable, purchasable,
  reason_code, source_path, source_locator, overlay_json
) VALUES
  ('UNIT', 'unit-sappers', 'ruleset-v5-core-curated-1', 'CATALOGUE_ONLY', 'BALANCE_REQUIRED', 'BLOCKED', 0, 0, 'RC_UNIT_015', 'rules/Classes.html', 'Sappers / row 8', '{"conflictIds":["RC-UNIT-015"],"gameplayGaps":["SAPPER_STRUCTURE_LIST","MINES","BUILD_SUPPLY","STEALTH_CONSTRUCTION"],"sourceExact":true}'),
  ('UNIT', 'unit-mechanized-infantry', 'ruleset-v5-core-curated-1', 'CATALOGUE_ONLY', 'BALANCE_REQUIRED', 'BLOCKED', 0, 0, 'RC_UNIT_015', 'rules/Classes.html', 'Mechanized Infantry / row 10', '{"conflictIds":["RC-UNIT-015"],"gameplayGaps":["FORWARD_LINE_CONTROL","MIXED_EQUIPMENT_POLICY","FS_VEHICLE_DAMAGE_MODEL"],"sourceExact":true}'),
  ('UNIT', 'unit-light-battle-tank', 'ruleset-v5-core-curated-1', 'CATALOGUE_ONLY', 'BALANCE_REQUIRED', 'BLOCKED', 0, 0, 'RC_UNIT_015', 'rules/Classes.html', 'Light Battle Tank / row 14', '{"conflictIds":["RC-UNIT-015"],"gameplayGaps":["FS_VEHICLE_DAMAGE_MODEL","WEAPON_DAMAGE_PROFILE","HAT_TANK_AIRDROP"],"sourceExact":true}'),
  ('UNIT', 'unit-heavy-battle-tank', 'ruleset-v5-core-curated-1', 'CATALOGUE_ONLY', 'BALANCE_REQUIRED', 'BLOCKED', 0, 0, 'RC_UNIT_015', 'rules/Classes.html', 'Heavy Battle Tank / row 16', '{"conflictIds":["RC-UNIT-015"],"gameplayGaps":["FS_VEHICLE_DAMAGE_MODEL","WEAPON_DAMAGE_PROFILE","HEAVY_TRANSPORT_POLICY"],"sourceExact":true}'),
  ('UNIT', 'unit-super-heavy-tank', 'ruleset-v5-core-curated-1', 'CATALOGUE_ONLY', 'BALANCE_REQUIRED', 'BLOCKED', 0, 0, 'RC_UNIT_015', 'rules/Classes.html', 'Super Heavy Tank / row 17', '{"conflictIds":["RC-UNIT-015"],"gameplayGaps":["FS_VEHICLE_DAMAGE_MODEL","DUAL_CANNON_ATTACK","WEAPON_DAMAGE_PROFILE","SPECIAL_TRANSPORT_POLICY"],"sourceExact":true}'),
  ('UNIT', 'unit-light-artillery', 'ruleset-v5-core-curated-1', 'CATALOGUE_ONLY', 'BALANCE_REQUIRED', 'BLOCKED', 0, 0, 'RC_UNIT_015', 'rules/Classes.html', 'Light Artillery / row 19', '{"conflictIds":["RC-UNIT-015"],"gameplayGaps":["FIXED_DAMAGE","TWO_ATTACK_SPLIT_FIRE","AREA_HEX_DAMAGE","ABANDON_GUNS","CAMPAIGN_REPLACEMENT"],"sourceExact":true}'),
  ('UNIT', 'unit-heavy-artillery', 'ruleset-v5-core-curated-1', 'CATALOGUE_ONLY', 'BALANCE_REQUIRED', 'BLOCKED', 0, 0, 'RC_UNIT_015', 'rules/Classes.html', 'Heavy Artillery / row 20', '{"conflictIds":["RC-UNIT-015"],"gameplayGaps":["FIXED_DAMAGE","THREE_ATTACK_SPLIT_FIRE","AREA_HEX_DAMAGE","ABANDON_GUNS","CAMPAIGN_REPLACEMENT"],"sourceExact":true}'),
  ('UNIT', 'unit-self-propelled-artillery', 'ruleset-v5-core-curated-1', 'CATALOGUE_ONLY', 'BALANCE_REQUIRED', 'BLOCKED', 0, 0, 'RC_UNIT_015', 'rules/Classes.html', 'Self-Propelled Artillery / row 21', '{"conflictIds":["RC-UNIT-015"],"gameplayGaps":["FS_VEHICLE_DAMAGE_MODEL","FIXED_DAMAGE","MINIMUM_RANGE","FINITE_AP_ROUNDS","AREA_HEX_DAMAGE"],"sourceExact":true}'),
  ('UNIT', 'unit-vtol-troop-airlift', 'ruleset-v5-core-curated-1', 'CATALOGUE_ONLY', 'BALANCE_REQUIRED', 'BLOCKED', 0, 0, 'RC_UNIT_015', 'rules/Classes.html', 'VTOL Heavy Troop Airlift / row 24', '{"conflictIds":["RC-UNIT-015"],"gameplayGaps":["FS_AEROSPACE_DAMAGE_MODEL","TROOP_OR_SUPPLY_CAPACITY","RAPPELLING_GARRISON","FS_BASED_REARM"],"sourceExact":true}'),
  ('UNIT', 'unit-vtol-multipurpose-airlift', 'ruleset-v5-core-curated-1', 'CATALOGUE_ONLY', 'BALANCE_REQUIRED', 'BLOCKED', 0, 0, 'RC_UNIT_015', 'rules/Classes.html', 'VTOL Multi-Purpose Airlift / row 25', '{"conflictIds":["RC-UNIT-015"],"gameplayGaps":["FS_AEROSPACE_DAMAGE_MODEL","SIMULTANEOUS_PERSONNEL_AND_VEHICLE_CARGO","FS_BASED_REARM"],"sourceExact":true}'),
  ('UNIT', 'unit-vtol-heavy-lift', 'ruleset-v5-core-curated-1', 'CATALOGUE_ONLY', 'BALANCE_REQUIRED', 'BLOCKED', 0, 0, 'RC_UNIT_015', 'rules/Classes.html', 'VTOL Heavy Lift / row 26', '{"conflictIds":["RC-UNIT-015"],"gameplayGaps":["FS_AEROSPACE_DAMAGE_MODEL","EXTERNAL_HEAVY_LIFT","OBJECTIVE_CARGO","HEAVY_TRANSPORT_CAPACITY"],"sourceExact":true}'),
  ('UNIT', 'unit-medium-mech', 'ruleset-v5-core-curated-1', 'CATALOGUE_ONLY', 'BALANCE_REQUIRED', 'BLOCKED', 0, 0, 'RC_UNIT_015', 'rules/Classes.html', 'Medium Mech / row 31', '{"conflictIds":["RC-UNIT-015"],"gameplayGaps":["FS_MECH_DAMAGE_MODEL","MULTIWEAPON_REFIT","LEG_HEIGHT_LOS","CROUCH_COVER","DOTTED_REQUISITION_COST"],"sourceExact":true}'),
  ('UNIT', 'unit-heavy-mech', 'ruleset-v5-core-curated-1', 'CATALOGUE_ONLY', 'BALANCE_REQUIRED', 'BLOCKED', 0, 0, 'RC_UNIT_015', 'rules/Classes.html', 'Heavy Mech / row 32', '{"conflictIds":["RC-UNIT-015"],"gameplayGaps":["FS_MECH_DAMAGE_MODEL","MULTIWEAPON_REFIT","LEG_HEIGHT_LOS","DOTTED_REQUISITION_COST"],"sourceExact":true}')
ON CONFLICT(definition_kind, definition_id, ruleset_id) DO UPDATE SET
  implementation_status=excluded.implementation_status, requisition_status=excluded.requisition_status,
  availability_status=excluded.availability_status, executable=excluded.executable,
  purchasable=excluded.purchasable, reason_code=excluded.reason_code,
  source_path=excluded.source_path, source_locator=excluded.source_locator, overlay_json=excluded.overlay_json;

-- Previously catalogued companion infantry are public reference entries too.
UPDATE ruleset_implementation_overlays
SET availability_status='BLOCKED', reason_code='RC_UNIT_015'
WHERE ruleset_id='ruleset-v5-core-curated-1' AND definition_kind='UNIT'
  AND definition_id IN ('unit-power-armoured-infantry','unit-irregular','unit-special-forces');
